### ISSUE TITLE
what's the indentation?

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#10]
This is super minor but I can't actually tell what you want here. All your examples have this formatting:

```
$ cargo vet
  error: cargo vet is not configured
```

Are you saying all output should be indented by 2 spaces, or is this purely an aesthetic thing you're doing in the docs (I think it's the latter, but, for a while I thought the former...).

**Comment by bholley** [comment]
I was pretty much just winging it with the docs. Would generally like to do whatever is most idiomatic.

**Comment by Gankra** [comment]
Gonna go with no-indent to start.
