### ISSUE TITLE
`cargo vet --locked` shouldn't compute suggestions

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#105]
When you `cargo vet` and it fails we automatically compute and emit `vet suggest`. A "first run" of suggest is incredibly expensive and it only gets more expensive the more audits you do. We mitigate this cost by having a diff-cache stored in the user's tmp, but CI is generally configured to work from a "clean slate" without explicit instructions to do otherwise. We could of course just ignore this but it seems like we'll need a better answer in the longterm.

Related but potentially distinct is just how slow a "first run" is for a local user.

There are two things that merit being cached:

* The fetches of packages to be diffed
* The diff-cache, which is just a simple json file containing the diff-stats of different package-version-pairs

We already have one mechanism for "save and restore" of the cache via the `--diff-cache=path/to/my_diff_cache.json`. We will try to read this file, and then write back all our computed diff-stats to it (creating it if it doesn't exist). So you can get some modicum of persistent caching by manually using --diff-cache and saving it somewhere between runs. Unfortunately we do not currently have a mechanism for "merging" or "locking" it so concurrency of individual runs is an open question.

We don't have the same functionality for the entire tmp cache dir (where the fetches are) but we could.

We don't have a mechanism for some "online global cache" that first-time-users can pull from, but we could.

**Comment by bholley** [comment]
So first, I think a "first run" is only incredibly slow in the case where you actually invoke `cargo vet suggest`. If you just get the suggestions from `cargo vet` after pulling in an unvetted dependency to a previously-passing tree (the likely situation on CI), only a handful of packages need to be fetched.

That said, some CI setups (including Mozilla's) aren't allowed to hit the network at all. So I think it makes the most sense for `--locked` to just not do the suggestions. It will tell you which crates are failing, and then you'd go run `cargo vet` locally to get the recommendations.

**Comment by bholley** [comment]
This is actually relevant to the current workstream of getting this running in Mozilla CI, so marking this as P1.
