### ISSUE TITLE
use `tracing` instead of `log`

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#106]
By all accounts `tracing` is better than bare `log`, and our error library is designed to interoperate with it. There's a compatibility shim so we can just s/log/tracing I *think* but I don't know enough about tracing to know if there's stuff we should do to really use it well (using its "spans" is probably a good idea...)

**Comment by bholley** [comment]
@Gankra this is done now right?

**Comment by Gankra** [comment]
yep
