### ISSUE TITLE
do we really want to suggest on vet?

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#11]
Suggest is a very heavy-weight command, are we sure we want to run it on every vet? (Downloading ~200 crates **twice**, decompressing them, diffing them... ouch.)

**Comment by bholley** [comment]
In addition to the optimization discussed in #6 , I think it'd also make sense to cache the number of lines of the crates and relevant diffs (which should presumably be immutable), in something like ~/.cargo-vet/cache.

**Comment by Gankra** [comment]
done
