### ISSUE TITLE
Implement proper locking of the cache

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#115]
Just as cargo must acquire a global system "lockfile" before accessing .cargo, so too should we before before accessing our own caches.

I have sketched out a place to do this here:

https://github.com/bholley/cargo-vet/blob/895992c364e079e07829aedb5f959d1b55ee064a/src/main.rs#L1569-L1572

But I don't know enough about the subtleties of lockfiles (which I hear are very cursed and messy) to implement this with my current knowledge.

We may also want a way to permit a kind of... read-write locking? Perhaps with merging? To allow for multiple concurrent runs to grab the current diff-cache, compute new values, and merge them back in?

This isn't a big deal right now since in CI with --locked we want #105 so there's no need to look at the cache at all. Of course in local usage if someone invokes `vet` multiple times it can lead to corruption of the cache, which, is not great? Although this might come into play more with certain versions of #85 where we try to "remember" what the last command is to automatically choose what is being certified, and the cache is the natural place to record that fact.

**Comment by bholley** [comment]
For now I think we should just do the dead-simple thing of creating a sentinel file and then deleting it. If the file already exists we just panic.

**Comment by bholley** [comment]
I think the standard way to do this is to have the panic message print the path to the culprit lockfile, and then the user can go delete it if needed.
