### ISSUE TITLE
what do you mean when you say something "defaults"

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#12]
Lots of lines like this:

> Specifies the relevant criteria for this audit. For version and delta entries, this defaults to the projects default criteria. For violation entries, this defaults to all defined criteria.

Is this indicating the entry is optional and we will infer these values when it's missing, or that the tool will auto-populate these values? (Is this the same answer for everywhere you use this terminology?)

**Comment by Gankra** [comment]
corollary: for fields like `unaudited.suggest` (default true), should the tool endeavour to omit the value whenever it would be the default, or shit it endeavour to always be as explicit as possible and make the value explicit?

(Since we're currently working under "autofmt always" this basically determines whether suggest=false is the only time you ever see the field.)

**Comment by bholley** [comment]
> Is this indicating the entry is optional and we will infer these values when it's missing, or that the tool will auto-populate these values? (Is this the same answer for everywhere you use this terminology?)

Generally speaking the former. I see value in having the .toml files not be unnecessarily verbose.

> corollary: for fields like `unaudited.suggest` (default true), should the tool endeavour to omit the value whenever it would be the default, or shit it endeavour to always be as explicit as possible and make the value explicit?
> 
> (Since we're currently working under "autofmt always" this basically determines whether suggest=false is the only time you ever see the field.)

Yes, we should omit values when they're not necessary. Otherwise there's a real impediment to adding new niche features (like suggest=false) because they balloon the config size.
