### ISSUE TITLE
Self-Hosting

### ISSUE THREAD

**Issue by bholley** [bholley/cargo-vet#14]
@Gankra I'm skeptical that we actually want the cargo-vet implementation to have its own supply-chain directory at this juncture. I can imagine two reasons for doing this.

The first is testing. For this, I think we'd be better off creating explicit synthetic test-cases, so that (1) there's no expectation that our audits will be true (e.g. we'll want to test `violation` without needing to find or construct an actually-malicious public crate), and (2) changes to the implementation don't disrupt our test coverage.

The second is a general "eating our own dogfood". I do think we'll eventually want to do this, but we'll want to align the criteria with Firefox's, and ideally put most of the actual audits in m-c (so that we consolidate availability for others).

So for now, I think we should focus on constructing synthetic test-cases to exercise the code and defer actually deploying vet on the implementation.

**Comment by Gankra** [comment]
I agree, I am mostly just checking in supply-chain to "see" what the output is in PRs/diffs while I still don't have proper testing infra setup (which seems like the right thing to punt on if you want an MVP asap).

**Comment by bholley** [comment]
Ok sure that's fine. As long as we're planning to migrate this into isolated test-cases at some point along the road here.
