### ISSUE TITLE
actual builtin criteria

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#15]
While this tool is ultimately herding cats and being opinionated is going to be Hard, it would genuinely be good to have the tool autopopulate some "builtin" criteria, I think? Like you can delete them or not use them if you want, but setting up criteria is a pain and I feel like there's *some* stuff that folks can agree on... or am I being too optimistic? Or alternatively, is this actually a trap and will lead to misunderstandings as people try to ram their process in the builtins for "compatability" and then suddenly no one agrees on what things mean?

**Comment by bholley** [comment]
This is now incorporated into the documentation.
