### ISSUE TITLE
questions on policies

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#19]
> By default, cargo vet checks all transitive dependencies of all top-level crates against the default criteria for all platforms. In some situations, you may be able to reduce your workload by encoding your requirements more precisely, such as:
>
>  Using different criteria for different top-level crates. Your workspace might contain both a production product and an internal tool, which might require different levels of audits for their dependencies.

I am not current aware of a mechanism for "using different criteria for different top-level crates". The design I have seen so far actually makes it *impossible* to talk about top-level crates, because they are definitionally not-third-party, and therefore completely ignored by all operations!

So policies let you set the default criteria everything must pass, but how *exactly* do you specify that a *crate* has a different policy?

# You can't specify that a crate should pass higher criteria

You can use dependency_criteria on *audits* to enforce that a dependency *edge* has a different policy, and by default an audit just projects its claimed criteria to all edges, so a load-bearing audit is *kind of* requiring that the crate meets that policy... but in a weird wobbly way that can be routed around. Like even if you have super-awesome-secure delta-audit, as long as your deps meet that criteria we'll happily walk through that audit even if this delta depends on weaker criteria because we're currently silently intersecting things and the final arbiter of if the result is "good enough" is still the `policy`.

# You can't specify that a crate can have lower criteria

The problem I see is that (as described in the book right now) your global policy is an effective *floor* on the criteria. If you say policy=super-awesome-secure, then it doesn't matter if you're fine with barely_used_dependency having criteria=not-obviously-a-virus, the policy will reject the crate, even if all the edges to it say it's ok for it to only be not-obviously-a-virus.

The only way to allow anything to have not-obviously-a-virus is to make the policy not-obviously-a-virus, but then you're making the checking on the root crates even weaker!

----------------

I'm not sure if you just haven't sketched this part out, or if it somehow made more sense to you when you were visualizing things top down, but I don't really know how to use this system right now.

**Comment by bholley** [comment]
> I am not current aware of a mechanism for "using different criteria for different top-level crates". The design I have seen so far actually makes it _impossible_ to talk about top-level crates, because they are definitionally not-third-party, and therefore completely ignored by all operations!
> 
> So policies let you set the default criteria everything must pass, but how _exactly_ do you specify that a _crate_ has a different policy?

So what I had in mind here, and what was not well-expressed in the text before, is that while audits can only apply to third-party crates, the algorithm traverses the entire tree. Because first-party crates are not of interest to external consumers, rules about them live in `config.toml` rather than `audits.toml`.

I updated the [relevant docs](https://bholley.net/cargo-vet/how-vetting-works.html#scope) to make this clearer. 

> The problem I see is that (as described in the book right now) your global policy is an effective _floor_ on the criteria. If you say policy=super-awesome-secure, then it doesn't matter if you're fine with barely_used_dependency having criteria=not-obviously-a-virus, the policy will reject the crate, even if all the edges to it say it's ok for it to only be not-obviously-a-virus.

I don't think this is quite right. In the formal model I proposed in the playground sketch, the policy determines what criteria must appear in the `subtree` array of the top-level nodes. The actual computation of subtree is recursive and can depend on the `dependency_criteria` specified at each node (along with any `criteria` in the policy table for first-party-but-not-top-level crates).

**Comment by Gankra** [comment]
Neither the playground nor this comment explains what you mean by "subtree array", but the docs you added to Policy make a lot more sense now. (Adding dependency_criteria to the config.toml also helps make this make more sense.)

It's still mildly confusing though, because nodes can't actually have a required criteria *in and of themselves*. Audits declare the criteria inferred by satisfying your dependency_criteria. So you still can't actually talk about the validated_criteria for a first-party crate without 'audits' entries to define them. 

Do you pick 'policy'? Do you pick 'all_criteria'? Should which of the two you pick ever effect the result? (Can someone define custom dependency_criteria between two first-party crates?) 

You might think that "the intersection of all dependency's validatd_criteria" is OK, but this doesn't really work in the face of being able to define non-uniform custom dependency_criteria.

Also just confirming: third-party crates don't need to conform to any particular policy at all, as long as all the edges bubble up to the first-party crates properly? Should it even be considered an error if a dependency satisfies no criteria as long as the first-party crates pass the policy? 

...Actually wait is a directly unaudited crate 'all_criteria' or 'no_criteria' or something else...? (Currently is 'all_criteria')

**Comment by bholley** [comment]
> Neither the playground nor this comment explains what you mean by "subtree array",

Not that it was very clear, but I was referring to this part of the napkin sketch:

> Next, compute |subtree| by iterating over |self_| and testing each entry against the
> already-computed |subtree| values of the node's children.

Basically I'm modeling this is a graph labeling algorithm, where each node has two lists of labels, |self| and |subtree|. The former is the list of criteria the crate-version has been audited for ignoring implicit and explicit dependency_criteria, the latter is the subset of the former that are still valid after having taken those into account.

> but the docs you added to Policy make a lot more sense now, so I can see you just mean "all non-third-party crates" (hereafter "first-party crates"). (Adding dependency_criteria to the config.toml also helps make this make more sense.)
> 
> It's still mildly confusing though, because nodes can't actually have a criteria _in and of themselves_. Audits declare the criteria inferred by satisfying your dependency_criteria. So you still can't actually talk about the validated_criteria for a first-party crate without 'audits' entries to define them.

Agreed. The semantics of the 'criteria' field in a policy entry are a subset of those for audit entries: the field is just the default value for all the implicit dependency_criteria entries.

> Do you pick 'policy'? Do you pick 'all_criteria'? Should which of the two you pick ever effect the result? (Can someone define custom dependency_criteria between two first-party crates?)

I think the validated criteria for a first-party node should be the union of all criteria.
 
> You might think that "the intersection of all dependency's validatd_criteria" is OK, but this doesn't really work in the face of being able to define non-uniform custom dependency_criteria.
> 
> Also just confirming: third-party crates don't need to conform to any particular policy at all, as long as all the edges bubble up to the first-party crates properly? Should it even be considered an error if a dependency satisfies no criteria as long as the first-party crates pass the policy?

Conceptually I think it's fine to specify an empty list in dependency_criteria, and would expect the tool to allow that. Practically speaking you're always going to want to at least audit the build script of any crate in your tree, but I don't think we need to encode that.
 
> ...Actually wait is a directly unaudited crate 'all_criteria' or 'no_criteria' or something else...? (Currently is 'all_criteria')

I don't parse "directly unaudited crate".

**Comment by Gankra** [comment]
directly unaudited = you have an audited entry for the exact version `vet` is trying to certify, so there are no audits to intersect the default 'all_criteria' with.

**Comment by bholley** [comment]
I think a directly unaudited crate should be all_criteria — same as first-party crates.
