### ISSUE TITLE
Implement approximate suggest for descendants of unaudited dependencies

### ISSUE THREAD

**Issue by bholley** [bholley/cargo-vet#32]
See (1) in the sketch at https://github.com/bholley/cargo-vet/issues/22#issuecomment-1100798406, and the ensuing discussion.

The current implementation landed in #31 makes no suggestions for such descendants (see the long comment).

**Comment by Gankra** [comment]
i haven't written tests for this but this should naturally fall out of unaudited entries now having criteria and therefore being desugarred to a full-audit with a flag noting that it would be nice to not use it.

**Comment by bholley** [comment]
> i haven't written tests for this but this should naturally fall out of unaudited entries now having criteria and therefore being desugarred to a full-audit with a flag noting that it would be nice to not use it.

I don't really parse this.

The current implementation doesn't do this at all because suggest doesn't traverse past unaudited dependencies. I think we actually want an option to do this (e.g. --deep), and then we'd need the approximation heuristic.

**Comment by Gankra** [comment]
oh this might be an ambiguity -- do you mean "dependencies that lack audits" or "dependencies with `unaudited` entries"

**Comment by bholley** [comment]
I meant "dependencies that lack audits" — since `cargo vet suggest` already eliminates all the `unaudited` entries.

Per matrix discussion, we're just going implement --deep in a criteria-less fashion for now.

**Comment by Gankra** [comment]
this is now implemented with `cargo vet suggest --guess-deeper`
