### ISSUE TITLE
Implement `cargo vet regenerate-unaudited`

### ISSUE THREAD

**Issue by bholley** [bholley/cargo-vet#33]
We can also add `cargo vet regenerate-unaudited` which computes the minimal unaudited list and puts it in policy.toml. cargo vet init implicitly does regenerate-unaudited, and will effectively use the defaults (safe-to-deploy for the main tree and safe-to-run for dev-and-build-dependencies)

**Comment by Gankra** [comment]
I added the criteria but haven't yet implemented regenerate

**Comment by bholley** [comment]
I think we actually want this sooner, because otherwise there's no way update unaudited after setting a laxer policy.

**Comment by bholley** [comment]
(i.e. for mozilla-central I want to set a policy for geckodriver of safe-to-run, but I can't subsequently generate a tighter unaudited after doing so).

**Comment by bholley** [comment]
Per our matrix discussion, the goal of this is to eliminate unaudited entries that are not required to make vetting pass. This includes potential replacements of criteria X with criteria Y when X implies Y, since the former is implicitly two entries where only one is required.

Replacing unaudited entry foo:a.b.c with foo:x.y.z is an anti-goal: it doesn't improve security and increases churn and potential confusion.

Here is my proposed algorithm for regenerate-unaudited:
(1) Read the old unaudited table as usual during startup.
(2) Run `cargo vet` with an empty unaudited table, and collect the set of missing audits.
(3) Transform that set of missing audits into a new unaudited table.
(4) Note that both tables may have multiple versions for a given crate, and multiple criteria. Treat the criteria as orthogonal (i.e. loop the rest of the algorithm for each criteria).
(5) For each crate in the new table, check if the old table has any entries for the same crate. If so, create an ordered list of all the versions for that crate that appear in both tables, with the entries from the old table appearing first. Remove all the entries for that crate from the new table.
(6) Loop over the above list in order (if it exists). For each entry, temporarily add it to the new table and re-run the resolver. If the failure count decreases, keep it. Otherwise, discard it. 

Assuming the above works, I think we may not need to expose it as a separate subcommand, and can instead just run it implicitly as part of `cargo vet`, and compare the tables at the end. If the tables are different, regular `cargo vet` will write the new one out, and `cargo vet --locked` will throw an error.

**Comment by bholley** [comment]
Fixed by #101 and #110.
