### ISSUE TITLE
When recommending an absolute audit, don't describe it as a delta audit

### ISSUE THREAD

**Issue by bholley** [bholley/cargo-vet#41]
Right now we have stuff like:

> cargo_metadata:0.14.2  0.0.0 -> 0.14.2 (15 files changed, 2103 insertions(+)) for ["safe-to-run", "safe-to-deploy"]

I think this should just say:

> cargo_metadata:0.14.2 (2103 lines)

**Comment by Gankra** [comment]
fixed in #44
