### ISSUE TITLE
config.toml tables should be optional

### ISSUE THREAD

**Issue by bholley** [bholley/cargo-vet#43]
If you do `cargo vet init` and then remove all the `unaudited` table entries, you end up implicitly removing the `unaudited` table itself, resulting in the following error when invoking `cargo vet`:

`Error: missing field `unaudited` at line 6 column 1`

This can be worked around by adding a dummy `[unaudited]` in the config file, but we should just make the tables optional.

**Comment by Gankra** [comment]
this should be fixed in #53

**Comment by bholley** [comment]
Confirmed fixed.
