### ISSUE TITLE
How "temp" should our temp fetches be?

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#6]
There's kind of 4 tiers of "temp" in my books:

1. So temp that it evaporates when the process exits
2. In your system "temp location" with a randomly generated directory name, so nothing can "know" where to find it, not even ourselves on subsequent runs (security people will be happy if you do this)
3. In your system "temp location" with a deterministic name
4. Actually not temp at all, just in the current working directory

I currently implement 3 with name "cargo-vet-checkout" because it's helpful for debugging, but 2 and 4 are both reasonable (your example output implies 3). 1 is totally gibberish for our usecase but I am pedant so I had to list it.

No matter what default we pick, we should absolutely expose a CLI flag for configuring this a little, if only so the user can opt into some flavour of 4 if they want.

Worth noting that something like `cargo vet suggest` is actually a very heavyweight process, because we basically need to download two separate copies of your crategraph and then individually diff each copy! This suggests it might be desirable to be able to cache results between runs, to some extent?

My current implementation is very conservative and will just completely destroy and recreate cargo-vet-checkout whenever anything wants to write results to temp (suggest, fetch, diff).

**Comment by Gankra** [comment]
Oh also in case you're wondering: I am currently entirely relying on hacky-but-maybe-actually-good solution where I generate a fresh Cargo.toml in the tempdir with the crates I want to download and run `cargo vendor` on it. (I do it really sloppily though, which is why it errors out with duplicate deps.)

Cargo's docs don't really talk about where it downloads things to, or how to find URLs. I know there is a stable URL schema for fetching crates, but then we need to implement the decompression and... idk why reinvent the wheel when Cargo literally exists to do this job?

**Comment by bholley** [comment]
That is a good question. I had mostly been thinking (3), but your point about caching is a good one, and so I went looking for prior art. 

It seems like `cargo crev` has an elegant solution here, which is to lean on the existing cargo cache in the user's home directory. Do you see any downsides to that approach?

https://github.com/crev-dev/cargo-crev/blob/master/cargo-crev/src/doc/getting_started.md#reviewing-code

**Comment by Gankra** [comment]
Oh yes, if we can actually reliably find this directory and ensure its contents are populated/unpacked, that is 100% the ideal solution, and might make commands like `suggest` lightweight enough to do more blithely.

**Comment by Gankra** [comment]
Hmm so ok:

* anything below the registry/ dir is officially unstable, but, there isn't much reason to change it (and lots of other people probably rely on it)
* unfortunately this stores the tar.xz(? need to look that up again) ".crate" files, so we do still need to create our own tempdir and unpack them there.

That said, the more I think about the implications of the vendor hack (and the fact that `cargo fetch` exists to guarantee the cache is populated), I'm pretty happy to use this. Will get that working today.

**Comment by Gankra** [comment]
Oh oops, no this is easier than I thought, was looking at the wrong dir (the struggle of unstable things... lack of docs)

**Comment by bholley** [comment]
And maybe in that case we should rename the command `cargo vet inspect`

**Comment by bholley** [comment]
This is now resolved.
