### ISSUE TITLE
Interactive input vs EDITOR?

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#7]
I am wondering if we actually want interactive prompts for things like `certify` or if we should do the `git commit` thing where we somehow launch your preferred EDITOR (or whatever the term is)?

Possible we want both options? (What would the default be?)

**Comment by bholley** [comment]
I'm not sure I follow what we'd use the editor for. Just typing 'yes'?

I was generally thinking `cargo vet certify` would default to the interactive prompt (that just spits out the criteria and requires the user type 'yes'), and then we could potentially add a --non-interactive flag that would bypass it. The interactivity exists primarily to ensure that new / infrequent users actually have the criteria text displayed to them.

**Comment by Gankra** [comment]
Ohhh. Ok I was reading the examples where it says "I, Alice, Certify..." as the equivalent of a commit message Alice was typing, but you're picturing this being more of the equivalent of a EULA prompt. I didn't see any mention of defining a message "template" (maybe I just glazed over that in criteria), so I'm not sure how that message would be generated.

So I guess you expect most certify's to have no interesting message/context, just "yep reviewed"? That's certainly very reasonable!

**Comment by bholley** [comment]
Yes, the template part is just what's in the docs ("I, Alice, certify that I have audited the changes between versions 1.2 and 1.2.1 of baz in accordance with the following criteria:"). And the ensuing text is just the criteria description, verbatim from `audits.toml`.
