### ISSUE TITLE
[book] clarify that the 'defaults' for policies are different for roots and non-roots

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#71]
Roots default to the stated defaults of safe-to-deploy or safe-to-run, but non-roots actually default to "wildcard policy" and just "inherit" the intersection of their children (with dependency_criteria policies marking passing children as all_criteria).

Full defining this requires #70 to be answered.

**Comment by bholley** [comment]
> Roots default to the stated defaults of safe-to-deploy or safe-to-run

Correct.

> but non-roots actually default to "wildcard policy" and just "inherit" the intersection of their children

They inherit the policy from their parents, not their children.

> (with dependency_criteria policies marking passing children as all_criteria).

I don't follow what this means.

[The current docs say](https://bholley.net/cargo-vet/config.html#the-policy-table):

> When unspecified, non-top-level first-party crates inherit policy attributes from their parents,
> whereas top-level first-party crates get the defaults described below.

This strikes me as clear enough, but maybe I'm missing something?

**Comment by bholley** [comment]
I think we're ok here but feel free to reopen if you disagree.
