### ISSUE TITLE
Implement checksums

### ISSUE THREAD

**Issue by bholley** [bholley/cargo-vet#79]
I've been asked about this a couple of times now. I don't think it's strictly necessary modulo crates.io compromise (at which point I contend you have bigger problems), but it also doesn't hurt, and I suspect it will be a frequently-enough requested feature that we might as well do it. And if we do it, we should do it now, before people generate a bunch of audit entries without checksums.

I've added it to the book [here](https://bholley.net/cargo-vet/audit-entries.html#checksum) and [here](https://bholley.net/cargo-vet/config.html#checksum).

Changes to make are:
- Mint the hashes in `cargo vet certify` and unaudited generation
- Trace the hashes through the version graph
- Match the hashes against the ones in the project

**Comment by Gankra** [comment]
Ok so cargo has the notion of a sha256 checksum which you can find both in the Cargo.lock as "checksum" as well as the [registry index](https://doc.rust-lang.org/cargo/reference/registries.html?highlight=checksum#index-format) as "cksum", and when it downloads a zipped `.crate` file from a registry it verifies that the computed checksum matches the expected one... and then it discards the computed checksum and unzips the thing and assumes nothing is tampered with.

It also has a more aggressive notion of checksuming for vendors, where it will construct a [.cargo-checksum.json](https://searchfox.org/mozilla-central/source/third_party/rust/alsa-sys/.cargo-checksum.json) file which contains a checksum of every file in the vendor. This is nominally just there to prevent accidentally modifying the vendor and creating infinite sadness for yourself.

We presumably want the former, but noting the latter for completeness.

I started sketching out the implementation of this and I think this is another feature which makes sense at first and then the more you work on it the more nonsensical it seems to become and now I'm not sure it makes any sense. Several questions need to be answered here:

* What exactly is the threat model we are trying to handle
* What exactly is the workflow being assumed here
* What exactly are we checksuming

All of these are... extremely not clear. When you type `cargo certify` there is no knowledge of how you did that audit. We do not require you to have fetched/diffed/inspected via cargo-vet. So what exactly are we sourcing our hash from? In increasing order of madness/messiness:

1. The crates.io registry at this precise moment in time? 
2. The sha256 hash of the .crate freshly downloaded from crates.io? 
3. The sha256 hash of the .crate in one of the two caches (cargo's and our own tmp one)?
4. The sha256 hash of the unpacked src?
    ...How? Cargo hashes the .crate file which is a .tar.gz and presumably it is non-trivial/impossible to locally reproduce since presumably the hashing algorithm/params are allowed to be updated over time.
    ...Note also that cargo makes subtle modifications to a repository when you publish, so the .crate's contents are not identical to what was in your directory when you hit `cargo publish`! (strips ignored files, rewrites your cargo.toml, adds some extra metadata files)
    ...Cargo also makes subtle modifications when you unpack the crate (adds .cargo-ok at very least)
  
Only (1) and (2) are coherent concepts without a connection between inspect/diff and certify. But they are also theoretically completely disconnected from what you actually reviewed. (3) is potentially connected but also "vulnerable" to local modifications... but so is any kind of attempt to do review! How paranoid is this system? And how is that level of paranoia actionable/useful?

**Comment by Gankra** [comment]
More broadly, it's unclear what a "hijack" or "hack" on the crates.io registry would look like such that you could change the SHA of a package and not have all the places that cargo itself checks SHAs not explode but have cargo-vet catch something? Like conceptually registries are append-only, so you "can't" modify a package, but I don't know if or how that's enforced/assumed/checked.

**Comment by bholley** [comment]
These are good points.

crates.io promises an immutable mapping from (crate, version) to package contents. If that holds, the hashes are superfluous. I can think of two cases where it might not hold.

The first is a global compromise scenario, in which somebody gains control of crates.io itself and is able to replace previously-released crates with malicious contents [1]. Since cargo checks the package contents against the checksums in the registry, the attacker would also need to modify the registry. But the registry is a github repo [2] that people all over the world fetch continuously, and so any history-rewrite would instantly cause widespread cargo errors and be detected. The attacker could create a regular commit to modify an existing entry, but since the index is supposed to be append-only (with the exception of setting 'yanked=true') [3], this is trivial to scan for, and anyone in the world could set up a script to do so on a continuous basis. So there isn't much of a role for `cargo vet` to play.

The second scenario is a split-view / MITM attack, wherein a network attacker serves malicious crates.io responses to a specific target. In theory checksums in `cargo vet` could help detect this inconsistency, but any attacker that could tamper with registry responses could also tamper with the checksums in imported audits (particularly since both the former and the latter are likely to be fetched from the same service, i.e. github). It would also just be a finicky attack to pull off: if you tamper with a crate whose hash was already in a local Cargo.lock or which was already in the local cargo cache, cargo would break. Likely simpler and more robust to just serve a malicious copy of rustc itself.

As such I can't really articulate what value this would provide. Anyone should feel free to chime in if there's something I've missed.

[1] Note that this is distinct from releasing a new malicious version of a popular crates, which `cargo vet` guards against irrespective of checksums.
[2] https://github.com/rust-lang/crates.io-index/commits/master
[3] https://doc.rust-lang.org/cargo/reference/registries.html#index-format

**Comment by tiziano88** [comment]
Thanks for the writeup, and for considering this feature.

I am starting to give cargo vet a try, but the fact that it stores and consumes audits based on anything other than checksums is a non-starter for us.

First of all, not all the crates we use are on crates.io.

Secondly, the audit should refer directly to what is being audited, without having to go through a dereference step that has crates.io as its root of trust. Content Addressability (i.e. identifying objects by their hash) is the de-facto standard and IMO the only sensible option when dealing with supply chain security. That also goes for git repositories and docker images; tags may be a convenience in order to find a reasonable checksum to start with, but they should never be trusted by themselves. This is already understood in the Rust ecosystem, and that's why Cargo.lock has explicit checksums for all crates (instead of just tags).

Would you be willing to reconsider this feature by any chance? I think it would make the story much more solid and valuable for a variety of use cases.

**Comment by bholley** [comment]
Note that crates.io isn't really a root of trust in the classical sense. Cargo-vet primarily just depends on the registry being (1) consistent across observers, and (2) append-only. If you have those properties, the hashes are implied —  and sprinkling copies of them in `audits.toml` doesn't buy you anything.

My thesis is that these properties are pretty hard to subvert in practice for crates.io. I could see avenues for strengthening and verifying them, but sense these are properties you want whether or not you're using cargo-vet, it strikes me as much more broadly useful to put such mechanisms in cargo itself (e.g. by replicating the index onto sigstore) rather than bolting them on here.

**Comment by kornelski** [comment]
Please reconsider this feature request. crates.io now uses a registry served over HTTP, and clients don't fetch the git registry any more. 

This means that GitHub doesn't act as a separate secure host any more. git doesn't act as as an immutable source of checksums (also crates.io has been squashing history in the git repo, so the history wasn't immutable even then). 

Serving of registry over HTTP allows targeted attacks. If the crates.io infrastructure was compromised, it would be possible to present different views of the registry to different clients, and have it go unnoticed.

----

In terms of implementation, I think `cargo-vet` can copy the `cksum` field from the registry to the audit files (and for delta reviews include checksums of both versions). `cargo-vet` fetches the registry metadata anyway, so it has these checksums available. The registry crate metadata file contains checksums for all versions of a crate, so checking them all doesn't add any extra traffic.

I'm not expecting this to provide security in situation when someone reviews crates after crates.io has already been compromised, but it could be a robust protection against crates.io getting compromised after the fact.

**Comment by kornelski** [comment]
Another reason to have checksums — crate name and version are *not* a unique identifier of a crates.io crate. This doesn't require crates.io getting hacked. It's an edge case in how crates.io currently operates. It's not a theoretical problem, there are many instances of previously published releases having their content replaced.

https://github.com/rust-lang/crates.io/discussions/11161

`(name, version, checksum)` should be the primary key for looking up crates:

https://github.com/rust-lang/crates.io/discussions/11161#discussioncomment-13222512
