### ISSUE TITLE
How to source "who"

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#8]
We discussed this a bit, and I vaguely recall that scraping git variables or something was a reasonable solution. Possible the book also covers it now. Filing this so I don't forget / we have somewhere to hang discussion.

**Comment by Gankra** [comment]
> A string identifying the auditor. When invoking cargo vet certify, the value is auto-populated from the global git config.

**Comment by bholley** [comment]
Yeah, the idea is to just use whatever `git commit` would stick into the `Author` field.
