### ISSUE TITLE
'vet certify' doesn't have any mechanism for specifying which criteria to certify

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#85]
Currently I just use the default one set in the config.toml, but presumably it should be possible to specify it on the CLI or in the prompt?

One kinda annoying thing for just making it an optional positional arg is that certify already has one in the form of "foo 1.0.0" vs "foo 1.0.0 1.1.0". Adding a second one would be mildly ambiguous and be annoying to untangle. I see a few options:

1. Magic: have two optional positional args and infer which is which based on trial-and-error parsing
2. Delta: write "1.0.0 1.1.0" as "1.0.0 -> 1.1.0" or something. Less "ambiguous" and more "terminals would hate that"
3. Named: use an optional named arg like --criteria=safe-to-run
4. Interactive: use the fact that we're already pulling up an interactive prompt to ask which they want (and if they just mash enter it picks the default)

There is also the question of how "multi-criteria" certification should work. The easiest answer is to not allow it and just ask the user to repeatedly invoke `certify`. The fancy answer is to accept multiple criteria and do multiple prompts (but under the hood it would still produce multiple new audit entries). Multiple criteria would be easiest to express with Named (3) as `clap` natively supports passing a flag repeatedly (which is more advisable than a single flag taking many args because that re-introduces positional ambiguities).

**Comment by Gankra** [comment]
Also I guess there's the question of if we should try to detect that a library is only used as a dev/build dep and default to safe-to-run but that sounds like a confusing/bad idea.

**Comment by bholley** [comment]
So here's my proposal.

First, we make the `certify` machinery capable of certifying multiple criteria at once. This would just interactively loop through the relevant EULAs.

Next, we add an explicit --criteria argument that allows specifying the certification criteria explicitly with one or more comma-separated strings.

When --criteria is not passed, `certify` should guess by internally invoking `cargo vet`. If the relevant audit shows up, we use the needed criteria. If it doesn't, we try again with `cargo vet suggest`. This handles the common case where somebody is doing a suggested audit for criteria that `cargo vet` has already identified.

Finally, if no guess is identified, we fall back to `safe-to-deploy`.

**Comment by bholley** [comment]
Oh! Oh! And we can add some additional magic wherein we persist the last `inspect` or `diff` command that was invoked, and then if you just bare-invoke `cargo vet certify` it can do the right thing.

**Comment by Gankra** [comment]
Alright gonna finally knock this out now that I've done a lot of the plumbing work. Friday I'll be doing basically Professional Development on our terminal library and terminal UX in general. So might take me more than one day to finish this.

(Will also involve rationalizing some of the deferred work on multiple criteria and potentially #78...)
