### ISSUE TITLE
incorrect parenthetical statistics

### ISSUE THREAD

**Issue by bholley** [bholley/cargo-vet#88]
STR:

(1) fresh mozilla-central checkout
(2) `cargo vet init`
(3) `cargo vet`

Result:

`Vetting Succeeded (144 fully audited, 0 partially audited, 383 unaudited)`

Not sure where that 144 is coming from but it seems wrong.

(Edit: I'd originally proposed a while-you're-at-it fix to not show partially audited crates unless there were a nonzero number of them, since I thought it would be rare. But I was thinking of the case where you require two criteria and only one of them is met (which I still think is rare), but realize now this probably refers to having audits for the right crate but the wrong version. That's actually probably pretty common, so I think it's fine to keep the current format unconditionally.)

**Comment by Gankra** [comment]
All first-party crates are regarded as "fully audited" when their policies pass. It's unclear whether they should ever be counted, or counted separately or what. It felt a bit weird to me to change the number in case of an error (since presumably first-parties would show up as failing...?)

**Comment by bholley** [comment]
I don't think the first-party crates should contribute to the count in either situation.

Suppose we have 3 different first-party crates, all of which depend on just one third-party crate foo. In either the audited or the unaudited case I think we should report "1".
