### ISSUE TITLE
Version specification questions

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#9]
We discussed this a fair bit, but I wanted to just file an issue where I can hang / save discussion on the matter.

# Conclusions I Recall Making

* It's nice to try to be compatible with Cargo's SemVer syntax wherever possible
* VersionReq ranges are usually a bad idea because of Time Travel (no one says release numbers have to always go up!)
  * Forbid is the one exception because being too broad is "fine"
    * Although this suggests you probably want a way to "override" a foreign forbid that is overbroad/capricious
    * Although `*` syntax and stuff is also just annoying to input in a terminal (book mentions this)
* Everything else should be a strict Version (one exact version, no weird syntax, -prerelease suffixes allowed)
* When following deltas during vetting, only exact matches are allowed (overlapping ranges allow for nasty "race conditions")

# Things I Am Fuzzy On That Might Be Explained In The Book Already

Several operations look at the current repo's state for crate versions, but there are actually several valid interpretations of that, in decreasing strictness:

1. The last succesfully vetted lockfile (what I currently save to Vetted.lock because I convinced myself that was useful)
2. The latest committed lockfile
3. The current lockfile (may have uncommited changes)
4. The current deps that Cargo would resolve if you did `cargo build` (deps may have been updated in Cargo.toml)

* [ ] Is there a universally correct choice? 
* [ ] If not, which commands want which ones? 
* [ ] Should we try to detect when any of these are *not* the same thing and emit a warning/error? 
  * Similar to how cargo publish refuses to run without a clean working directory.

**Comment by Gankra** [comment]
> Next, the files are ingested in order into a multi-level table, indexed first by crate name and then by criteria. Each concrete entry contains a list of absolute versions, a list of version deltas, a list of violation versions. **Each insertion checks for overlap between the set of audited versions and violation versions; if overlap is created, an error is thrown.**

So basically your entire project is considered malformed if an audit ever overlaps a violation (forbidden)? I suppose that makes sense.

**Comment by Gankra** [comment]
> If any entries in unaudited are superfluous — i.e. verification would succeed without them — a warning is generated so that the list can be pared down.

**Comment by bholley** [comment]
> We discussed this a fair bit, but I wanted to just file an issue where I can hang / save discussion on the matter.
> # Conclusions I Recall Making
> 
>     * It's nice to try to be compatible with Cargo's SemVer syntax wherever possible
> 
>     * VersionReq ranges are usually a bad idea because of Time Travel (no one says release numbers have to always go up!)
>       
>       * Forbid is the one exception because being too broad is "fine"
>         
>         * Although this suggests you probably want a way to "override" a foreign forbid that is overbroad/capricious
>         * Although `*` syntax and stuff is also just annoying to input in a terminal (book mentions this)
> 
>     * Everything else should be a strict Version (one exact version, no weird syntax, -prerelease suffixes allowed)
> 
>     * When following deltas during vetting, only exact matches are allowed (overlapping ranges allow for nasty "race conditions")
> 

This all sounds right to me.

> # Things I Am Fuzzy On That Might Be Explained In The Book Already
> 
> Several operations look at the current repo's state for crate versions, but there are actually several valid interpretations of that, in decreasing strictness:
> 
>     1. The last succesfully vetted lockfile (what I currently save to Vetted.lock because I convinced myself that was useful)

This one doesn't seem right to me semantically.

>     2. The latest committed lockfile

This seems like intermingling of concerns. I don't think `cargo vet` needs to be VCS-aware.

>     3. The current lockfile (may have uncommited changes)

I think this is the right default behavior.

>     4. The current deps that Cargo would resolve if you did `cargo build` (deps may have been updated in Cargo.toml)

Conceptually, it would be nice for `cargo vet` to warn/error if Cargo.toml hasn't been synced to Cargo.lock. I'm not sure how easy/performant that would be though, and in any case it's probably fine to skip for the MVP.

> So basically your entire project is considered malformed if an audit ever overlaps a violation (forbidden)? I suppose that makes sense.

Yes. I pondered whether you'd want some way to override certain imports (so that your development isn't blocked over a disagreement with another project about a forbidden range), but my sense is that forbidden entries will be very rare in practice, so I'm inclined to punt on it for now.

**Comment by Gankra** [comment]
this is all pretty clear in my mind now
