### ISSUE TITLE
Consider a mechanism to limit the addition of new dependencies on specific crates

### ISSUE THREAD

**Issue by mystor** [bholley/cargo-vet#95]
It might be nice to have some mechanism to prevent new dependency edges for certain crates being added without some additional work. This could be useful to require new code depending on an unaudited dependency to audit the dependency before being landed, to allow for a smoother transition to audited dependencies, or to allow marking a crate as only safe to use as a dependency in specific contexts (e.g. if a crate is approved only for use by a certain specific crate, because only some parts of the crate have actually been audited, and that crate has been checked to only use those features).

I'm not super sure what something like this could look like, but it may be reasonable to add an optional key to the audit log which if present is an allowlist of crate names which may depend on this crate.

**Comment by bholley** [comment]
Hah! I mid-aired with this in #96. Resolving this one.
